version: "3.8"

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - "./data:/data/db"
    restart: always

  server:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - mongo
    restart: always
